apiVersion: batch/v1
kind: CronJob
metadata:
  name: wiki
  namespace: project
spec:
  schedule: '0 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wiki
              image: mrousu/todo-wiki:cb93ecddc0980b4b6456333422bd18c0c8610cde
              env:
                - name: WIKI_URL
                  value: https://en.wikipedia.org/wiki/Special:Random
                - name: TODO_URL
                  value: http://todo-backend-svc:80/
          restartPolicy: OnFailure
