apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: project
spec:
  schedule: '0 0 * * *'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: mrousu/pg-dump:4
              env:
                - name: PGHOST
                  value: postgres-svc
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_USER
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /secrets/pg-dump-todos-key.json
                - name: BUCKET
                  value: gs://pg-dump-todos
              volumeMounts:
                - name: gcp-key
                  mountPath: /secrets
                  readOnly: true
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
                  FILE=/tmp/todo-backup-$TIMESTAMP.sql

                  gcloud auth list
                  gcloud auth activate-service-account pg-dump-todos@dwk-gke-481212.iam.gserviceaccount.com --key-file=/secrets/pg-dump-todos-key.json
                  gcloud auth list

                  echo "dumping"
                  pg_dump > $FILE

                  echo "uploading $BUCKET"
                  gsutil cp $FILE $BUCKET

                  echo "done: $FILE"
          volumes:
            - name: gcp-key
              secret:
                secretName: gcs-backup-sa
