apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rousumarkus-ctrl/kubernetes-config
    path: the-project/todo-app/overlays/staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
